version: '3'
services:
  ssh:
    build: ./ssh-host
    image: ssh-host
    labels:
      - traefik.enable=false

  ldap:
    image: osixia/openldap:1.2.2
    ports: 
      - 1389:389
    environment:
      - LDAP_DOMAIN=sailpoint.demo
      - LDAP_ORGANISATION=Sailpoint Demo
      - LDAP_ADMIN_PASSWORD=spadmin
    deploy:
      labels: 
        - traefik.enable=false

  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=id3ntityIQ
      - MSSQL_PID=Developer
    deploy:
      labels:
        - traefik.enable=false

  db_mysql:
    image: "mysql:${MYSQL_VERSION:-5.7}"
    environment:
      - MYSQL_USER=identityiq
      - MYSQL_PASSWORD=identityiq
      - MYSQL_DATABASE=identityiq
      - MYSQL_ROOT_PASSWORD=password
    deploy:
      labels: 
        - traefik.enable=false

  mail:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - "${MAILHOG_HTTP_PORT:-8025}:8025"
    deploy:
      labels:
        - traefik.enable=false

  lb2:
    image: traefik
    command: --docker --docker.swarmMode --docker.domain=traefik --docker.watch --api --web
    #command: --api --docker --web --logLevel=DEBUG
    ports:
      - "${LISTEN_PORT:-8080}:80"      # The HTTP port
      - "28080:8080"  # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # So that Traefik can listen to the Docker events
    deploy:
      labels:
        - traefik.enable=false

  iiq-master:
    build: ./iiq-build
    image: identityworksllc/sailpoint-iiq
    environment:
      - DATABASE_TYPE=mssql
      - MSSQL_USER=identityiq
      - MSSQL_PASS=Id3ntityiq
      - MSSQL_SA_PASSWORD=id3ntityIQ
      - "MYSQL_HOST=db_mysql"
      - MYSQL_USER=identityiq
      - MYSQL_PASSWORD=identityiq
      - MYSQL_DATABASE=identityiq
      - MYSQL_ROOT_PASSWORD=password
      - IIQ_VERSION=7.2
      - IIQ_PATCH=${IIQ_PATCH}
    ports:
      - 8880:8080
    depends_on:
      - db
      - mail
      - ldap
    deploy:
      labels:
        - traefik.backend=iiq
        - traefik.port=8080
        - traefik.docker.network=frontend
        - "traefik.frontend.rule=PathPrefix:/identityiq"
        - "traefik.backend.loadbalancer.sticky=true"
